version: '2'
services:
  node:
    build: ./app
    ports:
     - "8100:8100"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./app/api:/app/api
  db:
    build: ./db
